// src/constants/colombiaData.ts
export const departamentosColombia = [
    'Amazonas',
    'Antioquia',
    'Arauca',
    'Atlántico',
    'Bogotá D.C.',
    'Bolívar',
    'Boyacá',
    'Caldas',
    'Caquetá',
    'Casanare',
    'Cauca',
    'Cesar',
    'Chocó',
    'Córdoba',
    'Cundinamarca',
    'Guainía',
    'Guaviare',
    'Huila',
    'La Guajira',
    'Magdalena',
    'Meta',
    'Nariño',
    'Norte de Santander',
    'Putumayo',
    'Quindío',
    'Risaralda',
    'San Andrés y Providencia',
    'Santander',
    'Sucre',
    'Tolima',
    'Valle del Cauca',
    'Vaupés',
    'Vichada'
  ];
  
  export const ciudadesColombia = [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Bucaramanga',
    'Pereira',
    'Santa Marta',
    'Manizales',
    'Villavicencio',
    'Pasto',
    'Montería',
    'Valledupar',
    'Buenaventura',
    'Neiva',
    'Armenia',
    'Popayán',
    'Sincelejo',
    'Ibagué',
    'Barranca de upia',
    'Yopal',
    'Villanueva'
  ];
  
  export const bancosColombia = [
    'Bancolombia',
    'Banco de Bogotá',
    'Davivienda',
    'BBVA',
    'Banco de Occidente',
    'Banco Popular',
    'Banco Caja Social',
    'Banco Agrario',
    'Banco AV Villas',
    'Banco GNB Sudameris',
    'Banco Falabella',
    'Bancoomeva',
    'Banco Pichincha',
    'Banco Serfinanza',
    'Banco W',
    'Banco Finandina',
    'Citibank',
    'Banco Santander',
    'Banco Itaú',
    'Banco Colpatria',
    'Nequi',
    'Daviplata',
    'RappiPay',
    'Movii',
    'Nu Colombia (Nubank)',
    'Bancoomeva',
    'Coopcentral',
    'Cafam',
    'Colpatria Cooperativa',
    'Cotrafa',
    'Fondo Nacional del Ahorro (FNA)'
];